const mongoose = require("mongoose");

/**
 * Event Schema for MongoDB using Mongoose.
 * 
 * @typedef {Object} Event
 * @property {String} name - The name of the event. Required.
 * @property {String} description - A brief description of the event. Required.
 * @property {Date} date - The date of the event. Required.
 * @property {String} time - The time of the event. Required.
 * @property {String} [image] - An optional image URL for the event.
 * @property {String} location - The location where the event will take place. Required.
 * @property {String} category - The category of the event. Required.
 * @property {Array.<mongoose.Schema.Types.ObjectId>} attendees - An array of user IDs who are attending the event.
 * @property {mongoose.Schema.Types.ObjectId} organizer - The user ID of the event organizer. Required.
 * @property {Date} createdAt - The date and time when the event was created. Automatically generated by Mongoose.
 * @property {Date} updatedAt - The date and time when the event was last updated. Automatically generated by Mongoose.
 */
const eventSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  description: {
    type: String,
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  time: {
    type: String,
    required: true
  },
  image: {
    type: String,
    required: false
  },
  location: {
    type: String,
    required: true
  },
  category: {
    type: String,
    required: true
  },
  attendees: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  }],
  organizer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true
  }
}, { timestamps: true });

module.exports = mongoose.model("Event", eventSchema);